### ISSUE TITLE
一部ファイルのパスがおかしい

### ISSUE THREAD

**Issue by i17305** [ichi-raven/Cpps-chalenge#2]
https://github.com/ichi-raven/Cpps-chalenge/blob/master/C%2B%2B's%20chalenge.vcxproj#L32
こことか
https://github.com/ichi-raven/Cpps-chalenge/blob/master/C%2B%2B's%20chalenge.vcxproj.filters#L30
こことか
何故か一部ファイルが相対パスで指定されてるのでプロジェクトフォルダの名前を変えると読み込めない。
修正すべきファイルは以下の通り。

- BCmanager.cpp
- BCmanager.hpp
- define.hpp
- jiki.cpp
- jiki.hpp
- jiki_shotmanager.hpp
- gamemode.cpp

**Comment by ichi-raven** [comment]
直してみます 失礼しました・・・

**Comment by i17305** [comment]
なおった
